<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
/**
 *
 *	C  O M M   W I T H   C L I E N T S
 *
 */
 	/** Documents */
	
	/** Header */
	/** nothing ! logo assumed meltilungual */
	
	/** Header Doc */
	'Comments' => 'Commentaires',
	'Date' => 'Date',
	'Note' => 'Note',
	'Object' => 'Objet',
	'Reference Client' => 'Référence Client',
	'Reference Operation' => 'A rappeler lors du paiement',
	'Subject' => 'Sujet',
	'VAT Client' => 'TVA Client',
	'VAT Number' => 'Numéro TVA',
	'Order' => 'Commande',
	
	/** Body */
	
	/** Item Details*/
	'Price Chassis' => 'Prix Châssis',
	'Price Chroma' => 'Prix ChromaLuxe',
	'Price Collage' => 'Prix Collage',
	'Price Corner' => 'Prix Coins arrondis',
	'Price Filmuv' => 'Prix Film UV',
	'Price Finish' => 'Prix Finition',
	'Price Frame' => 'Prix Encadrement',
	'Price List' => 'Liste de prix',
	'Price Lists' => 'Listes de prix',
	'Price Montage' => 'Prix Montage',
	'Price Protection' => 'Prix Protection',
	'Price Renfort' => 'Prix Renforts',
	'Price Support' => 'Prix Support',
	'Price Tirage' => 'Prix Tirage',
	'Chroma Type' => 'Type de ChromaLuxe',
	'White Glossy' => 'Blanc Brillant',
	'White Mat' => 'Blanc Mat',
	'Clear Glossy' => 'Transparent Brillant',
	'Clear Mat' => 'Transparent Mat',

	'Price HTVA' => 'Prix HTVA',
	'Price Htva' => 'Prix HTVA',
	'Price TVAC' => 'Prix TVAC',
	'Price TVAC' => 'Prix TVAC',
	'Price' => 'Prix',
	'Total Htva' => 'Total HTVA',
	'Total TVAC' => 'Total TVAC',
	'Htva' => 'Hors TVA',
	'Total' => 'Total',
	
	'Account' => 'Compte',
	'Bill Date' => 'Facturation',
	'Bill Sent' => 'Facturé',
	'Due Date' => 'Livraison',
	'Extra' => 'Extra', // remise, supplément, etc.
	'Item'	=> 'Article',
	'Items' => 'Articles',
	'Label' => 'Libellé',
	'Order Date' => 'Commande',
	'Quantity' => 'Quantité',
	'REFN' => 'Numéro de référence',
	'Rebate' => 'Remise',
	'Rebate/Supplement' => 'Remise/Supplément',
	'Reference' => 'Référence',
	'Supplement' => 'Supplément',
	'Unit Price' => 'Prix unitaire',

	'Bill' => 'Facture',
	'Order Due Date' => 'Livraison commande',
	'Bill Issue Date' => 'Facture émise',
	'Bill Due Date' => 'Echéance facture',
	'Due' => 'Dû',
	
		
	/** Abbreviations (entêtes de colonnes) */
	'Qty' => 'Qté',		//'Quantité',
	'Ref.' => 'Réf.',	//'Reference',
	'U.Pc' => 'P.Un',	//Unit Price
	'Printed on' => 'Imprimé le ',
	'All price VAT excluded.' => 'Prix HTVA.',
	
	/** Footer Doc */
	'Advance' => 'Acompte',
	'Advances' => 'Acomptes',
	'Amount' => 'Montant',
	'Created At' => 'Créé le',
	'Due Date' => 'Livraison',
	'Legal' => 'Mention Légale',
	'Paid Today' => "Payé aujourd'hui",
	'Prepaid' => 'Acompte',
	'Solde' => 'Solde',
	'Taxable' => 'Imposable',
	'Thank You' => 'Merci',
	'To Pay' => 'A payer',
	'Updated At' => 'Mise à jour',
	'VAT Rate' => 'Taux',
	'VAT' => 'TVA',
	'VAT excl.' => 'HTVA',
	'VAT incl.' => 'TVAC',
	'Number' => 'Numéro',
	
	
	
	
	/** Footer */
	'Labo JJ Micheli SPRL • 21-23 rue de Tervaete • 1040 Brussels<br>Tél. +32 (0)2 733 21 85 • Fax. +32 (0)2 733 38 72<br>e-Mail: info@labojjmicheli.be • Web Site: www.labojjmicheli.be • VAT: BE 0428 746 631 RPM: BXL<br>BNP Paribas Fortis Bank 210-0381493-44 • IBAN: BE55 2100 3814 9344 • BIC: GEBABEBB' => 'Labo JJ Micheli SPRL • 21-23 rue de Tervaete • 1040 Bruxelles<br>Tél. +32 (0)2 733 21 85 • Fax. +32 (0)2 733 38 72<br>e-Mail: info@labojjmicheli.be • Site Web: www.labojjmicheli.be • TVA: BE 0428 746 631 RPM: BXL<br>Banque BNP Paribas Fortis 210-0381493-44 • IBAN: BE55 2100 3814 9344 • BIC: GEBABEBB',


	/** Mails */
	'Your account statement.' => 'Votre extrait de compte.',
	'Please read attached document(s).' => 'Veuillez lire le(s) document(s) joint(s) à ce message. Merci.',
	'Unpaid Bills' => 'Factures impayées',

	'STD_SIGNATURE' => "Veuillez, s'il vous plaît, vérifier votre commande, les dimensions, et les options de finition. Veuillez également rappeler le numéro du bon de commande lors de toutes communications et lors du paiement de l'acompte. Merci.",

	/** Letters: Headings, subjects, date, place & Footers */
	'Brussels, {0}' => 'Bruxelles, le {0}',
	'Your Client Account' => 'Votre compte client',
	'Unbalanced Orders' => 'Extrait de compte',
	'Last Update' => 'Dernière MàJ',
	'Late Unpaid Bills - 2nd Reminder' => 'Factures impayées - Deuxième Rappel',
	'Late Unpaid Bills - Last Reminder' => 'Factures impayées - Dernier Rappel',
	'Late Unpaid Bills' => 'Factures impayées',


	/** Letters: General texts & watermarks */
	'FRAME_ORDERS::BEFORE_LIST' => "Veuillez trouver en annexe la liste des cadres que nous commandons.",
	'FRAME_ORDERS::AFTER_LIST'  => " ",
	'FRAME_ORDERS::CALL_ACTION' => "Pour toute question, n'hésitez pas à nous contacter au numéro de téléphone 02&nbsp;/&nbsp;733&nbsp;21&nbsp;85, du lundi au vendredi, entre 8h30 et 18h30.",
	'FRAME_ORDERS::GREETINGS' => "Commercialement vôtre.</p><p>Pour Labo JJ. Micheli,",



	'ACCOUNT_UNBALANCED::AFTER_LIST' => " ",
	'ACCOUNT_UNBALANCED::BEFORE_LIST' => "Nous nous référons à notre précédent relevé de compte resté sans suite à ce jour. Nous nous permettons de vous rappeler avec insistance les factures ci-dessous arrivées à échéance.",
	'ACCOUNT_UNBALANCED::CALL_ACTION' => "Nous vous demandons d'avoir l'obligeance de régulariser votre situation immédiatement. Si votre paiement a été exécuté entre-temps, vous voudrez bien ne pas tenir compte du présent rappel.",
	'ACCOUNT_UNBALANCED::GREETINGS' => "Dans l'attente de votre réponse, veuillez agréer, Madame, Monsieur, l'expression de nos sentiments distingués.</p><p>Pour Labo JJ. Micheli,<br />La comptabilité.",

	'Reminder Type 0' => 'Duplicatat',
	'Duplicate' => 'Duplicatat',
	'LATE_BILL_COVER0::AFTER_LIST'  => "Supposant qu’il s’agit d’un oubli de votre part, nous vous serions gré d’effectuer le paiement dans les plus brefs délais sur notre compte <strong>BE55 2100 3814 9344</strong>.",
	'LATE_BILL_COVER0::BEFORE_LIST' => "Sauf erreur de notre part, l’examen de nos comptes montre que les factures suivantes sont impayées.",
	'LATE_BILL_COVER0::CALL_ACTION' => "Si entre temps vous aviez procédé au paiement, veuillez considérer la présente comme nulle.",
	'LATE_BILL_COVER0::GREETINGS' => "En vous remerciant d’avance, veuillez agréer, Madame, Monsieur, nos salutations distinguées.</p><p>Pour Labo JJ. Micheli,",

	'Reminder Type 1' => 'Rappel',
	'Reminder' => 'Rappel',
	'LATE_BILL_COVER1::AFTER_LIST'  => "Supposant qu’il s’agit d’un oubli de votre part, nous vous serions gré d’effectuer le paiement dans les plus brefs délais sur notre compte <strong>BE55 2100 3814 9344</strong>.",
	'LATE_BILL_COVER1::BEFORE_LIST' => "Sauf erreur de notre part, l’examen de nos comptes montre que les factures suivantes sont impayées.",
	'LATE_BILL_COVER1::CALL_ACTION' => "Si entre temps vous aviez procédé au paiement, veuillez considérer la présente comme nulle.",
	'LATE_BILL_COVER1::GREETINGS' => "En vous remerciant d’avance, veuillez agréer, Madame, Monsieur, nos salutations distinguées.</p><p>Pour Labo JJ. Micheli,",

	'Reminder Type 2' => 'Deuxième rappel',
	'2nd Reminder' => 'Deuxième Rappel',
	'LATE_BILL_COVER2::AFTER_LIST'  => "Supposant qu’il s’agit d’un oubli de votre part, nous vous serions gré d’effectuer le paiement dans les plus brefs délais sur notre compte <strong>BE55 2100 3814 9344</strong>.",
	'LATE_BILL_COVER2::BEFORE_LIST' => "Sauf erreur de notre part, l’examen de nos comptes montre que les factures suivantes sont impayées.",
	'LATE_BILL_COVER2::CALL_ACTION' => "Si entre temps vous aviez procédé au paiement, veuillez considérer la présente comme nulle.",
	'LATE_BILL_COVER2::GREETINGS' => "En vous remerciant d’avance, veuillez agréer, Madame, Monsieur, nos salutations distinguées.</p><p>Pour Labo JJ. Micheli,",

	'Reminder Type 3' => 'Dernier rappel',
	'Last Reminder' => 'Dernier Rappel',
	'LATE_BILL_COVER3::AFTER_LIST'  => "Sans régularisation de votre part dans les 15 jours nous serons obligé de confier votre dossier au tribunal compétent, tous frais à votre charge.",
	'LATE_BILL_COVER3::BEFORE_LIST' => "Malgré nos derniers rappels, nous n’avons toujours pas été crédité de vos paiements (*).",
	'LATE_BILL_COVER3::CALL_ACTION' => "Si vous estimez qu’un problème quelconque vous empêche de vous acquitter de cette dette, veuillez prendre contact avec notre service comptable au plus tôt au n°&nbsp;de tel 02&nbsp;/&nbsp;733&nbsp;21&nbsp;85.",
	'LATE_BILL_COVER3::GREETINGS' => "(*) Voir annexe(s) jointe(s).</p><p>Pour Labo JJ. Micheli,",

	
	/** Document Types and Statuses */
	'ACREDIT' => 'Crédit',
	'ADEBIT' => 'Débit',
	'ACTIVE' => 'Actif',
	'BALANCED' => 'Payé',
	'BID' => 'Devis',
	'BILL' => 'Facture',
	'BILLED' => 'Facturé',
	'BOM' => 'Bon de livraison',
	'BUSY' => 'Réalisation',
	'CANCELLED' => 'Annulé',
	'CLOSED' => 'Clôturé',
	'COMMANDE' => 'Commande',
	'CREATED' => 'Créé',
	'CREDIT' => 'Note de crédit',
	'DELIVERED' => 'Livré',
	'DEVIS' => 'Devis',
	'DONE' => 'Terminé',
	'FACTURE' => 'Facture',
	'NOTIFY' => 'Avertir',
	'NOTIFIED' => 'Envoyé',
	'OPEN' => 'Ouverte',
	'ORDER' => 'Commande',
	'PAID' => 'Payé',
	'PENDING' => 'En attente',
	'RETIRED' => 'Retiré',
	'TICKET' => 'Ticket de vente',
	'TOPAY' => 'A payer',
	'TODO' => 'A faire',
	'WORK' => 'En traitement',
	'REFUND' => 'Remboursement',

	'Quotes' => 'Devis',
	'Good Received' => 'Livré',

	
];
