<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
/**
 *
 *	C O M M   W I T H   C L I E N T S
 *
 */
 	/** Documents */
	
	/** Header */
	/** nothing ! logo assumed meltilungual */
	
	/** Header Doc */
	'Comments' => 'Opmerkingen',
	'Date' => 'Datum',
	'Note' => 'Nota',
	'Object' => 'Betreft',
	'Reference Client' => 'Klantreferentie', // 'Uw Referentie',
	'Reference Operation' => 'Referentie voor betaling', // 'Referentie nummer',
	'Subject' => 'Betreft',
	'VAT Client' => 'BTW Klant',
	'VAT Number' => 'BTW Nummer',
	'Number' => 'Nummer',
	'Order' => 'Bestelling',
	
	/** Body */
	
	/** Item Details*/
	'Price Chassis' => 'Prijs Kader',
	'Price Chroma' => 'Prijs ChromaLuxe',
	'Price Collage' => 'Prijs Collage',
	'Price Corner' => 'Prijs Afgeronde hoeken',
	'Price Filmuv' => 'Prijs UV Film',
	'Price Finish' => 'Prijs Afwerking',
	'Price Frame' => 'Prijs Kader',
	'Price List' => 'Prijslijst',
	'Price Lists' => 'Prijslijsten',
	'Price Montage' => 'Prijs Montage',
	'Price Protection' => 'Prijs Beschermingslaag',
	'Price Renfort' => 'Prijs Versterking',
	'Price Support' => 'Prijs Steunvlak',//**
	'Price Tirage' => 'Prijs Afdruk',
	'Chroma Type' => 'ChromaLuxe Type',
	'White Glossy' => 'Wit Glanzend',
	'White Mat' => 'Wit Mat',
	'Clear Glossy' => 'Doorschijnend Glanzend',
	'Clear Mat' => 'Doorschijnend Mat',

	'Price HTVA' => 'Prijs excl.BTW',
	'Price TVAC' => 'Prijs incl.BTW',
	'Price' => 'Prijs',
	'Total HTVA' => 'Totaal excl.BTW',
	'Total TVAC' => 'Totaal incl.BTW',
	'VAT excl.' => 'excl.BTW',
	'VAT incl.' => 'incl.BTW',
	'Total' => 'Totaal',
	'VAT' => 'BTW',
	
	'Account' => 'Rekening',
	'Bill Date' => 'Facturatie',
	'Bill Sent' => 'Gefactureerd',
	'Due Date' => 'Vervaldatum', // 'Leveringsdatum',
	'Extra' => 'Extra', // remise, supplément, etc.
	'Item'	=> 'Artikel',//Product/Dienst
	'Items' => 'Artikelen',
	'Label' => 'Product/Dienst',
	'Order Date' => 'Bestellingsdatum',
	'Quantity' => 'Aantal',
	'REFN' => 'Referentie nummer',
	'Rebate' => 'Korting',
	'Rebate/Supplement' => 'Korting/Extra',
	'Reference' => 'Referentie',
	'Supplement' => 'Extra',
	'Unit Price' => 'Eenheidsprijs',

	'Bill' => 'Faktuur',
	'Order Due Date' => 'Leveringsdatum',
	'Bill Issue Date' => 'Gefactureerd',
	'Bill Due Date' => 'Vervaldatum',
	'Due' => 'Te betalen',	
	
	
	/** Abbreviations (entêtes de colonnes) */
	'Qty' => 'Aantal',		//'Quantité',
	'Ref.' => 'Ref.',	//'Reference',
	'U.Pc' => 'Prijs',	//Unit Price
	'Printed on' => 'Afgedrukt op ',
	
	/** Footer Doc */
	'Advance' => 'Voorschot',
	'Advances' => 'Voorschotten',
	'Amount' => 'Bedrag',
	'Created At' => 'Créé le',//**
	'Legal' => 'Juridische kennisgeving',//wettelijke opmerking
	'Paid Today' => "Vandaag betaald",
	'Prepaid' => 'Gestort Voorschot', // 'Voorschotten',
	'Solde' => 'Te betalen Saldo',
	'Taxable' => 'Belastbaar',
	'Thank You' => 'Dank U',
	'To Pay' => 'Te betalen',
	'Updated At' => 'Laaste update',
	'VAT Rate' => '% BTW',
	'VAT' => 'BTW',
	'Vat' => 'BTW',
	'Rate' => '% BTW',
	
	/** Footer */
	'Labo JJ Micheli SPRL • 21-23 rue de Tervaete • 1040 Brussels<br>Tél. +32 (0)2 733 21 85 • Fax. +32 (0)2 733 38 72<br>e-Mail: info@labojjmicheli.be • Web Site: www.labojjmicheli.be • VAT: BE 428 746 631 RPM: BXL<br>BNP Paribas Fortis Bank 210-0381493-44 • IBAN: BE55 2100 3814 9344 • BIC: GEBABEBB' => 'Labo JJ Micheli SPRL • 21-23 Tervaetestraat • 1040 Brussel<br>Tel. +32 (0)2 733 21 85 • Fax. +32 (0)2 733 38 72<br>e-Mail: info@labojjmicheli.be • Web Site: www.labojjmicheli.be • BTW: BE 428 746 631 RPM: BXL<br>BNP Paribas Fortis Bank 210-0381493-44 • IBAN: BE55 2100 3814 9344 • BIC: GEBABEBB',


	/** Mails */
	'Your account statement.' => 'Uw rekening uitreksels.',
	'Unpaid Bills' => 'Niet betaalde facturen',
	'Please read attached document(s).' => 'Gelieve hierbij gevoegde dokumenten te lezen. Dank U.',

	'STD_SIGNATURE' => "Kunt u, alstublieft, controle meting en afwerkingsopties. Vermeld uw ordernummer in alle communicatie en betalingen. Dank U.",

	/** Letters: Headings, subjects, date, place & Footers */
	'Brussels, {0}' => 'Brussel, {0}',
	'Your Client Account' => 'Uw klant rekening',
	'Unbalanced Orders' => 'Niet betaalde facturen',//**
	'Last Update' => 'Dernière MàJ',
	'Late Unpaid Bills - 2nd Reminder' => 'Niet betaalde facturen - Tweede Herinnering',
	'Late Unpaid Bills - Last Reminder' => 'Niet betaalde facturen - Laatste Herinnering',
	'Late Unpaid Bills' => 'Niet betaalde facturen',
	'Reminder' => 'Herinnering',


	/** Letters: General texts & watermarks */
	'ACCOUNT_UNBALANCED::BEFORE_LIST' => "Bij controle van uw rekening in onze boeken bemerken wij dat een bedrag nog open staat. Het betreft met de volgende factuur(s):",
	'ACCOUNT_UNBALANCED::AFTER_LIST'  => "Mogen wij u verzoeken deze zaak na te zien en het genoemde bedrag over te schrijven op onze rekening <strong>BE55 2100 3814 9344</strong>.",
	'ACCOUNT_UNBALANCED::CALL_ACTION' => "Indien u deze betaling intussen reeds zou hebben uitgevoerd, gelieve u deze herinnering als niet geschreven te beschouwen.",
	'ACCOUNT_UNBALANCED::GREETINGS' => "Met hoogachting,</p><p>Voor Labo JJ. Micheli,",

	'Reminder Type 0' => 'Duplicatat',
	'Duplicate' => 'Duplicatat',
	'LATE_BILL_COVER0::BEFORE_LIST' => "Bij controle van uw rekening in onze boeken bemerken wij dat een bedrag nog open staat. Het betreft met de volgende factuur(s):",
	'LATE_BILL_COVER0::AFTER_LIST'  => "Mogen wij u verzoeken deze zaak na te zien en het genoemde bedrag over te schrijven op onze rekening <strong>BE55 2100 3814 9344</strong>.",
	'LATE_BILL_COVER0::CALL_ACTION' => "Indien u deze betaling intussen reeds zou hebben uitgevoerd, gelieve u deze herinnering als niet geschreven te beschouwen.",
	'LATE_BILL_COVER0::GREETINGS' => "Met hoogachting,</p><p>Voor Labo JJ. Micheli,",

	'Reminder Type 1' => 'Rappel',
	'Reminder' => 'Rappel',
	'LATE_BILL_COVER1::BEFORE_LIST' => "Bij controle van uw rekening in onze boeken bemerken wij dat een bedrag nog open staat. Het betreft met de volgende factuur(s):",
	'LATE_BILL_COVER1::AFTER_LIST'  => "Mogen wij u verzoeken deze zaak na te zien en het genoemde bedrag over te schrijven op onze rekening <strong>BE55 2100 3814 9344</strong>.",
	'LATE_BILL_COVER1::CALL_ACTION' => "Indien u deze betaling intussen reeds zou hebben uitgevoerd, gelieve u deze herinnering als niet geschreven te beschouwen.",
	'LATE_BILL_COVER1::GREETINGS' => "Met hoogachting,</p><p>Voor Labo JJ. Micheli,",

	'Reminder Type 2' => 'Deuxième rappel',
	'2nd Reminder' => 'Deuxième Rappel',
	'LATE_BILL_COVER2::BEFORE_LIST' => "Uit onze boekhouding blijkt dat, ondanks onze herinneringsbrief van verlede maand, volgende facturen nog niet betaald zijn:",
	'LATE_BILL_COVER2::AFTER_LIST'  => "Wij verzoeken u dan ook met aandrang het achterstallige bedrag per kerende te betalen op onze rekening nr <strong>BE55 2100 3814 9344</strong>.",
	'LATE_BILL_COVER2::CALL_ACTION' => "U zal ongetwijfeld begrijpen dat wij genoodzaakt zijn de strikte naleving van onze betalingsvoorwaarden te eisen.  D.w.z. dat intresten verschuldigd zullen zijn.",
	'LATE_BILL_COVER2::GREETINGS' => "Hoogachtend,</p><p>Voor Labo JJ. Micheli,",

	'Reminder Type 3' => 'Dernier rappel',
	'Last Reminder' => 'Dernier Rappel',
	'LATE_BILL_COVER3::BEFORE_LIST' => "Ondanks herhaalde herinneringen blijkt uit mijn boekhouding dat de volgende factuur nog steeds niet betaald is:",
	'LATE_BILL_COVER3::AFTER_LIST'  => "Bij deze brief wil ik u een laatste keer verzoeken dit bedrag over te maken op mijn rekeningnummer <strong>BE55 2100 3814 9344</strong>.",
	'LATE_BILL_COVER3::CALL_ACTION' => "Te uwer informatie verwijs ik hierbij naar art. E. van onze algemene verkoopsvoorwaarden.",
	'LATE_BILL_COVER3::GREETINGS' => "Hoogachtend,</p><p>Voor Labo JJ. Micheli,",

	
	/** Document Types and Statuses */
	'ACREDIT' => 'Krediet',
	'ADEBIT' => 'Debiet',
	'ACTIVE' => 'Actief',
	'BALANCED' => 'Betaald',
	'BID' => 'Devis',
	'BILL' => 'Factuur',
	'BILLED' => 'Gefactureerd',
	'BOM' => 'Leveringsbon',
	'BUSY' => 'In bewerking',
	'CANCELLED' => 'Geannuleerd',
	'CLOSED' => 'Afgewerkt',
	'COMMANDE' => 'Bestelling',
	'CREATED' => 'Aangemaakt',
	'CREDIT' => 'Kredietnota',
	'DELIVERED' => 'Geleeverd',
	'DEVIS' => 'Offerte',
	'DONE' => 'Afgewerkt',
	'FACTURE' => 'Factuur',
	'NOTIFIED' => 'Verwittigd',
	'OPEN' => 'Open',
	'ORDER' => 'Bestelling',
	'PAID' => 'Betaald',
	'PENDING' => 'In afwachting',
	'RETIRED' => 'Teruggetrokken',
	'TICKET' => 'Ticket',
	'TOPAY' => 'Te Betalen',
	'TODO' => 'Nog te starten',
	'WORK' => 'In bewerking',
	'SENT' => 'Gestuurd',
	'INDISPONIBLE' => 'Niet beschikbaar',

	'Quotes' => 'Offerte',
	'Good Received' => 'Geleeverd',

	
];
