<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'STD_SIGNATURE' => "Dear,

Please find attached your order form or quote.  Would you please be so kind to check all the elements (paper type, dimensions, finishing options) ?
If you have any corrections or comments on this, please contact us on 010/45 97 77 or by mail at info@colorfields.be
If it is perfectly correct, please pay a 50% deposit by resuming the structured communication included in this document.

Best Regards,

COLORFIELDS srl
Avenue Franklin 4 b 19
1300 Wavre
010/45 97 77
www.colorfields.be",

'STD_SIGNATURE_HTML' => "<p>Dear,</p>
<br/>
Please find attached your order form or quote.  Would you please be so kind to check all the elements (paper type, dimensions, finishing options) ?</p>
<p>If you have any corrections or comments on this, please contact us on 010/45 97 77 or by mail at info@colorfields.be.</p>
<p>If it is perfectly correct, please pay a 50% deposit by resuming the structured communication included in this document.</p>
</br>
<p>Best Regards,</p>
</br>
</br>
<p style='font-weight: bolder'>COLORFIELDS srl
<br/>Avenue Franklin 4 b 19
<br/>1300 Wavre
<br/>010/45 97 77</p>
<p><a href='https://www.colorfields.be/en/colorfields-fine-art-printing/'>www.colorfields.be</a>"


];
